<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<meta name="generator" content="Bloc de notas" /> 
	<meta name="author" content="Carlos y Marcos" /> 
	<meta name="keywords" content="HTML5, web" /> 
	<meta name="description" content="Esta es la pagina creada para las practicas de la asignatura de DAW" /> 

	<title>PI - Pictures & Images</title>

	
	<!--<link rel = "stylesheet" type = "text/css" href = "css/adapter.css" title="Estilo accesible" media="screen"/> -->
	<link rel = "stylesheet" type = "text/css" href = "css/impresion.css" media="print"/> 
	<!--<link rel = "stylesheet" type = "text/css" href = "css/responsive.css" media="screen">-->
	<link rel = "stylesheet" type = "text/css" href = "/daw/css/estilo.css" media="screen" />

</head>